version: '2.4'
services:
  postgres:
    container_name: postgres
    image: postgres:10.10
    restart: always
    environment:
      - POSTGRES_USER=blockscout
      - POSTGRES_PASSWORD=blockscout
      - POSTGRES_DB=blockscout
    volumes:
      - ./blockscout/postgresql:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    network_mode: "host"
  app:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      - MIX_ENV=prod
      - COIN=LA
      - ETHEREUM_JSONRPC_HTTP_URL=http://116.203.75.72:7070
      - ETHEREUM_JSONRPC_VARIANT=ganache
      - DATABASE_URL=postgresql://blockscout:blockscout-dev-postgresql:5432/blockscout?ssl=false
      - BLOCKSCOUT_HOST=postgres
    network_mode: "host"
