version: '2.4'
services:
  postgresql:
    container_name: blockscout-dev-postgresql
    image: postgres:10.10
    command: postgres -c 'max_connections=1024'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blockscout
      - POSTGRES_PASSWORD=blockscout
      - POSTGRES_DB=blockscout
    volumes:
      - ./blockscout/postgresql:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    # network_mode: "host"
  app:
    build:
      # network: host
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgresql
    environment:
      - MIX_ENV=prod
      - COIN=LA
      - ETHEREUM_JSONRPC_HTTP_URL=https://rpc-testnet.lachain.io
      - ETHEREUM_JSONRPC_VARIANT=ganache
      - DATABASE_URL=postgresql://blockscout:blockscout@blockscout-dev-postgresql:5432/blockscout?ssl=false
      - BLOCKSCOUT_HOST=localhost
      - SUBNETWORK=Devnet
      - DATABASE_HOST=blockscout-dev-postgresql
      - HIDE_BLOCK_MINER=true
