ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
  hosts:
    default: blockscout-{env}.dev3.nekotal.tech
  paths:
    value: "/"
  servicePort: 4000

replicaCount: 1
image:
  repository: harbor.nekotal.tech/dev-middleware/blockscout
  tag: dev
  pullPolicy: IfNotPresent
ports:
  containerPort: 4000
resources:
  limits:
   cpu: 700m
   memory: 1Gi
  requests:
   cpu: 700m
   memory: 1Gi

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

configmap:
  POSTGRES_ADDRESS:
    default: "jdbc:postgresql://blockscout:blockscout@blockscout-{env}-postgresql:5432/blockscout"
  POSTGRES_USER:
    default: "blockscout"
  POSTGRES_PASSWORD:
    default: "blockscout"
  POSTGRES_DB:
    default: "blockscout"
  MIX_ENV:
    default: "prod"
  COIN:
    default: "LA"
  ETHEREUM_JSONRPC_HTTP_URL:
    default: "http://116.203.75.72:7070"
    dev: "http://116.203.75.72:7070"
    test: "http://95.217.12.226:7070"
  ETHEREUM_JSONRPC_VARIANT:
    default: "ganache"
  DATABASE_URL:
    default: "postgresql://blockscout:blockscout@blockscout-{env}-postgresql:5432/blockscout?ssl=false"
  DATABASE_HOST:
    default: "blockscout-{env}-postgresql"
  BLOCKSCOUT_HOST:
    default: "postgres"
  SUBNETWORK:
    default: "Devnet"
    dev: "Devnet"
    test: "Testnet"


postgresql:
  enabled: true
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    persistentVolumeReclaimPolicy: Delete
  postgresqlUsername: blockscout
  postgresqlPassword: blockscout
  postgresqlDatabase: blockscout
  postgresqlPostgresPassword: blockscout
  metrics:
    enabled: false
