ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
  hosts:
    dev: lachain-blockscout.dev3.nekotal.tech
    qa: lachain-blockscout-qa.dev3.nekotal.tech
  paths:
    value: "/"
  servicePort: 4000

replicaCount: 1
image:
  repository: harbor.nekotal.tech/dev-middleware/blockscout
  tag: dev
  pullPolicy: IfNotPresent
ports:
  containerPort: 4000
nodeSelector:
  node.selector/app: middleware
resources:
  # limits:
  #  cpu: 700m
  #  memory: 1Gi
  # requests:
  #  cpu: 700m
  #  memory: 1Gi

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

configmap:
  POSTGRES_ADDRESS:
    dev: "jdbc:postgresql://blockscout:@blockscout-dev-postgresql:5432/blockscout"
    qa: "jdbc:postgresql://blockscout:@blockscout-qa-postgresql:5432/blockscout"
  POSTGRES_USER:
    dev: "blockscout"
    qa: "blockscout"
  POSTGRES_PASSWORD:
    dev: "blockscout"
    qa: "blockscout"
  POSTGRES_DB:
    dev: "blockscout"
    qa: "blockscout"
  MIX_ENV:
    dev: "prod"
    qa: "prod"
  COIN:
    dev: "LA"
    qa: "LA"
  ETHEREUM_JSONRPC_HTTP_URL:
    dev: "http://116.203.75.72:7070"
    qa: "http://116.203.75.72:7070"
  ETHEREUM_JSONRPC_VARIANT:
    dev: "ganache"
    qa: "ganache"
  DATABASE_URL:
    dev: "postgresql://blockscout:blockscout@blockscout-dev-postgresql:5432/blockscout?ssl=false"
    qa: "postgresql://blockscout:blockscout@blockscout-qa-postgresql:5432/blockscout?ssl=false"
  DATABASE_HOST:
    dev: "blockscout-dev-postgresql"
    qa: "blockscout-qa-postgresql"
  BLOCKSCOUT_HOST:
    dev: "postgres"
    qa: "postgres"


postgresql:
  enabled: true
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
  postgresqlUsername: blockscout
  postgresqlPassword: blockscout
  postgresqlDatabase: blockscout
  postgresqlPostgresPassword: blockscout
  metrics:
    enabled: false
  nodeSelector:
    node.selector/app: middleware
