ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
  secretName: certificate-production
  hosts:
    dev: lachain-blockscout.dev3.nekotal.tech
  paths:
    value: "/"
  servicePort: 4000

replicaCount: 1
image:
  repository: harbor.nekotal.tech/dev-middleware/blockscout
  tag: dev
  pullPolicy: IfNotPresent
ports:
  containerPort: 4000
nodeSelector:
  node.selector/app: middleware
resources:
  # limits:
  #  cpu: 700m
  #  memory: 1Gi
  # requests:
  #  cpu: 700m
  #  memory: 1Gi

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

configmap:
  POSTGRES_ADDRESS:
    dev: "jdbc:postgresql://blockscout:@blockscout-dev-postgresql:5432/blockscout"
  POSTGRES_USER:
    dev: "blockscout"
  POSTGRES_PASSWORD:
    dev: "blockscout"
  POSTGRES_DB:
    dev: "blockscout"
  MIX_ENV:
    dev: "prod"
  COIN:
    dev: "LA"
  ETHEREUM_JSONRPC_HTTP_URL:
    dev: "http://116.203.75.72:7070"
  ETHEREUM_JSONRPC_VARIANT:
    dev: "ganache"
  DATABASE_URL:
    dev: "postgresql://blockscout:@blockscout-dev-postgresql:5432/blockscout?ssl=false"
  DATABASE_HOST:
    dev: "blockscout-dev-postgresql"
  BLOCKSCOUT_HOST:
    dev: "postgres"


postgresql:
  enabled: true
  postgresInitdbArgs: --data-checksums
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    storageClass: longhorn
  postgresqlUsername: blockscout
  postgresqlPassword: blockscout
  postgresqlDatabase: blockscout
  metrics:
    enabled: false
  nodeSelector:
    node.selector/app: middleware
  pgHbaConfiguration: |
    host all all all trust
    host all all 127.0.0.1/32 trust
