# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}
  labels:
    app.kubernetes.io/name:  {{ .Release.Name }}
    helm.sh/chart: {{ include "blockscout.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  POSTGRES_ADDRESS: {{ pluck .Values.global.env .Values.configmap.POSTGRES_ADDRESS | first | default .Values.configmap.POSTGRES_ADDRESS.dev }}
  POSTGRES_USER: {{ pluck .Values.global.env .Values.configmap.POSTGRES_USER | first | default .Values.configmap.POSTGRES_USER.dev }}
  POSTGRES_PASSWORD: {{ pluck .Values.global.env .Values.configmap.POSTGRES_PASSWORD | first | default .Values.configmap.POSTGRES_PASSWORD.dev }}
  POSTGRESQL_POSTGRES_PASSWORD: {{ pluck .Values.global.env .Values.configmap.POSTGRESQL_POSTGRES_PASSWORD | first | default .Values.configmap.POSTGRESQL_POSTGRES_PASSWORD.dev }}
  POSTGRES_DB: {{ pluck .Values.global.env .Values.configmap.POSTGRES_DB | first | default .Values.configmap.POSTGRES_DB.dev }}
  MIX_ENV: {{ pluck .Values.global.env .Values.configmap.MIX_ENV | first | default .Values.configmap.MIX_ENV.dev }}
  COIN: {{ pluck .Values.global.env .Values.configmap.COIN | first | default .Values.configmap.COIN.dev }}
  ETHEREUM_JSONRPC_HTTP_URL: {{ pluck .Values.global.env .Values.configmap.ETHEREUM_JSONRPC_HTTP_URL | first | default .Values.configmap.ETHEREUM_JSONRPC_HTTP_URL.dev }}
  ETHEREUM_JSONRPC_VARIANT: {{ pluck .Values.global.env .Values.configmap.ETHEREUM_JSONRPC_VARIANT | first | default .Values.configmap.ETHEREUM_JSONRPC_VARIANT.dev }}
  DATABASE_URL: {{ pluck .Values.global.env .Values.configmap.DATABASE_URL | first | default .Values.configmap.DATABASE_URL.dev }}
  BLOCKSCOUT_HOST: {{ pluck .Values.global.env .Values.configmap.BLOCKSCOUT_HOST | first | default .Values.configmap.BLOCKSCOUT_HOST.dev }}
